# Generated by Django 3.2.4 on 2022-10-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221031_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user/default.png', null=True, upload_to='user/<function User.image at 0x7f896ddca510>'),
        ),
    ]
