version: '3.8'

services:
  web:
    image: mendozarain/exactbooks-backend:0.1
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    expose:
      - 8000
    ports:
      - 8000:8000