# Generated by Django 3.2.4 on 2022-10-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='books/<function Book.image at 0x7fe4da584f28>'),
        ),
    ]
