# Generated by Django 3.2.4 on 2022-10-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='books/<function Book.image at 0x7fadfbcaf490>'),
        ),
    ]
