# Generated by Django 3.2.4 on 2022-10-31 09:03

import books.models
import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='plot',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='books/default_cover.png', null=True, storage=core.mixins.OverwriteStorage(), upload_to=books.models.path_and_rename),
        ),
    ]
